### ISSUE TITLE
Killer info box sometimes remains visible for longer than it should

### ISSUE THREAD

**Issue by DESTROYGIRL** [bauxiteDYS/SM-NT-Killer-Info#2]
Sometimes the killer info box will persist into the start of the next round and prevent switching weapons which can mess up rollouts.
At worst it can linger until I'm killed again in the new round. It's pretty rare but has happened throughout the entire time I've been playing on servers with the plugin enabled.

**Comment by bauxiteDYS** [comment]
As far as I understand, and it appears to work in testing, `SendPanelToClient(panel, client, Handler_DoNothing, 20);` means the panel will timeout after 20s.  

I can't get it to stick around any longer, this means it should usually have no affect on your rollout as the freezetime is 15s, I suppose it might linger around for 5s into the round if you died right before the new round starts. So lowering it to under 15s might fix the issue.

However if you can make the panel stick around longer than 20s, that seems like a bug and if you could reproduce that, it would be really helpful.
